const elements = [
    { 
    n: 1, s: "H", name: "Hydrogen", r: 1, c: 1, cat: "nonmetal", 
    config: "1s¹",
    wikiData: {
        appearance: "Khí không màu, phát sáng tím ở thể plasma",
        mass: "1,00794(7)",
        phase: "Chất khí",
        melting: "14,01 K (-259,14 °C)",
        boiling: "20,28 K (-252,87 °C)",
        density: "0,08988 g/L",
        discovery: "Henry Cavendish (1766)",
        namedBy: "Antoine Lavoisier (1783)",
        oxidation: "1, 0, -1 (Lưỡng tính)",
        electronegativity: "2,20 (Pauling)"
    }
    },
    { n: 2, s: "He", name: "Helium", r: 1, c: 18, cat: "noble", config: "1s²",
    wikiData: {
        appearance: "Khí không màu, phát sáng vàng nhạt ở thể plasma",
        mass: "4,002602(2)",
        phase: "Chất khí",
        melting: "0,95 K (-272,20 °C) (áp suất cao)",
        boiling: "4,22 K (-268,93 °C)",
        density: "0,1786 g/L",
        discovery: "Pierre Janssen và Norman Lockyer (1868)",
        namedBy: "Norman Lockyer (1868)",
        oxidation: "0",
        electronegativity: "Không có giá trị (không phản ứng)"
    }
    },
    { n: 3, s: "Li", name: "Lithium", r: 2, c: 1, cat: "alkali", config: "[He] 2s¹" ,
    wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "6,94(1)",
        phase: "Chất rắn",
        melting: "453,65 K (180,50 °C)",
        boiling: "1603 K (1330 °C)",
        density: "0,534 g/cm³",
        discovery: "Johan August Arfwedson (1817)",
        namedBy: "Johan August Arfwedson (1817)",
        oxidation: "1",
        electronegativity: "0,98 (Pauling)"
    }
    },
    { n: 4, s: "Be", name: "Beryllium", r: 2, c: 2, cat: "alkaline", config: "[He] 2s²",
    wikiData: {
        appearance: "Kim loại cứng, màu xám thép",
        mass: "9,012182(3)",
        phase: "Chất rắn",
        melting: "1560 K (1287 °C)",
        boiling: "2742 K (2469 °C)",
        density: "1,85 g/cm³",
        discovery: "Friedrich Wöhler và Antoine Bussy (1828)",
        namedBy: "Friedrich Wöhler và Antoine Bussy (1828)",
        oxidation: "2",
        electronegativity: "1,57 (Pauling)"
    }
    },
    { n: 5, s: "B", name: "Boron", r: 2, c: 13, cat: "semimetal", config: "[He] 2s² 2p¹",
    wikiData: {
        appearance: "Rắn, màu nâu sẫm",
        mass: "10,81(1)",
        phase: "Chất rắn",
        melting: "2349 K (2076 °C)",
        boiling: "4200 K (3927 °C)",
        density: "2,34 g/cm³",
        discovery: "Joseph Louis Gay-Lussac và Louis Jacques Thénard (1808)",
        namedBy: "Jöns Jacob Berzelius (1808)",
        oxidation: "3",
        electronegativity: "2,04 (Pauling)"
    }
    },
    { n: 6, s: "C", name: "Carbon", r: 2, c: 14, cat: "nonmetal", config: "[He] 2s² 2p²", wikiData: {
        appearance: "Có nhiều dạng thù hình: kim cương (trong suốt), than chì (đen), graphene (trong suốt)",
        mass: "12,011(1)",
        phase: "Chất rắn",
        melting: "3823 K (3550 °C) (áp suất cao)",
        boiling: "4098 K (3825 °C) (áp suất cao)",
        density: "2,267 g/cm³ (than chì), 3,51 g/cm³ (kim cương)",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-4, -3, -2, -1, 0, +1, +2, +3, +4",
        electronegativity: "2,55 (Pauling)"
    }
    },
    { n: 7, s: "N", name: "Nitrogen", r: 2, c: 15, cat: "nonmetal", config: "[He] 2s² 2p³", wikiData: { 
        appearance: "Khí không màu, không mùi",
        mass: "14,007(1)",
        phase: "Chất khí",
        melting: "63,15 K (-210,00 °C)",
        boiling: "77,36 K (-195,79 °C)",
        density: "1,2506 g/L",
        discovery: "Daniel Rutherford (1772)",
        namedBy: "Jean-Antoine Chaptal (1790)",
        oxidation: "-3, -2, -1, 0, +1, +2, +3, +4, +5",
        electronegativity: "3,04 (Pauling)"
    }
    },
    { n: 8, s: "O", name: "Oxygen", r: 2, c: 16, cat: "nonmetal", config: "[He] 2s² 2p⁴", wikiData: {
        appearance: "Khí không màu, không mùi",
        mass: "15,999(1)",
        phase: "Chất khí",
        melting: "54,36 K (-218,79 °C)",
        boiling: "90,20 K (-182,95 °C)",
        density: "1,429 g/L",
        discovery: "Carl Wilhelm Scheele (1772), Joseph Priestley (1774)",
        namedBy: "Antoine Lavoisier (1777)",
        oxidation: "-2, -1, 0, +1, +2",
        electronegativity: "3,44 (Pauling)"
    }
    },
    { n: 9, s: "F", name: "Fluorine", r: 2, c: 17, cat: "halogen", config: "[He] 2s² 2p⁵", wikiData: {
        appearance: "Khí vàng nhạt, có mùi hăng",
        mass: "18,998403163(6)",
        phase: "Chất khí",
        melting: "53,48 K (-219,67 °C)",
        boiling: "85,03 K (-188,12 °C)",
        density: "1,696 g/L",
        discovery: "Henri Moissan (1886)",
        namedBy: "Henri Moissan (1886)",
        oxidation: "-1",
        electronegativity: "3,98 (Pauling)"
    }
    },
    { n: 10, s: "Ne", name: "Neon", r: 2, c: 18, cat: "noble", config: "[He] 2s² 2p⁶", wikiData: {
        appearance: "Khí không màu, không mùi",
        mass: "20,1797(6)",
        phase: "Chất khí",
        melting: "24,56 K (-248,59 °C)",
        boiling: "27,07 K (-246,08 °C)",
        density: "1,783 g/L",
        discovery: "William Ramsay và Morris Travers (1898)",
        namedBy: "William Ramsay (1898)",
        oxidation: "0",
        electronegativity: "0 (Pauling)"
    }
    },

    { n: 11, s: "Na", name: "Sodium", r: 3, c: 1, cat: "alkali", config: "[Ne] 3s¹", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "22,98976928(2)",
        phase: "Chất rắn",
        melting: "370,87 K (97,72 °C)",
        boiling: "1156 K (883 °C)",
        density: "0,968 g/cm³",
        discovery: "Humphry Davy (1807)",
        namedBy: "Humphry Davy (1807)",
        oxidation: "1",
        electronegativity: "0,93 (Pauling)"
    }
    },
    { n: 12, s: "Mg", name: "Magnesium", r: 3, c: 2, cat: "alkaline", config: "[Ne] 3s²", wikiData: {
        appearance: "Kim loại nhẹ, màu bạc sáng",
        mass: "24,305(6)",
        phase: "Chất rắn",
        melting: "923 K (650 °C)",
        boiling: "1363 K (1090 °C)",
        density: "1,738 g/cm³",
        discovery: "Joseph Black (1755)",
        namedBy: "Joseph Black (1755)",
        oxidation: "2",
        electronegativity: "1,31 (Pauling)"
    }
     },
    { n: 13, s: "Al", name: "Aluminium", r: 3, c: 13, cat: "basic-metal", config: "[Ne] 3s² 3p¹", wikiData: {
        appearance: "Kim loại nhẹ, màu bạc sáng",
        mass: "26,9815385(7)",
        phase: "Chất rắn",
        melting: "933,47 K (660,32 °C)",
        boiling: "2792 K (2519 °C)",
        density: "2,70 g/cm³",
        discovery: "Hans Christian Ørsted (1825)",
        namedBy: "Hans Christian Ørsted (1825)",
        oxidation: "3",
        electronegativity: "1,61 (Pauling)"
    }
    },
    { n: 14, s: "Si", name: "Silicon", r: 3, c: 14, cat: "semimetal", config: "[Ne] 3s² 3p²", wikiData: {
        appearance: "Rắn, màu xám kim loại",
        mass: "28,085(1)",
        phase: "Chất rắn",
        melting: "1687 K (1414 °C)",
        boiling: "3538 K (3265 °C)",
        density: "2,33 g/cm³",
        discovery: "Jöns Jacob Berzelius (1824)",
        namedBy: "Jöns Jacob Berzelius (1824)",
        oxidation: "-4, 0, +2, +4",
        electronegativity: "1,90 (Pauling)"
    }
    },
    { n: 15, s: "P", name: "Phosphorus", r: 3, c: 15, cat: "nonmetal", config: "[Ne] 3s² 3p³", wikiData: {
        appearance: "Có nhiều dạng thù hình: trắng (sáp, phát sáng), đỏ (rắn, không phát sáng), đen (rắn, không phát sáng)",
        mass: "30,973761998(5)",
        phase: "Chất rắn",
        melting: "317,30 K (44,15 °C) (phosphorus trắng)",
        boiling: "553 K (280 °C) (phosphorus trắng)",
        density: "1,82 g/cm³ (phosphorus trắng), 2,34 g/cm³ (phosphorus đỏ), 2,69 g/cm³ (phosphorus đen)",
        discovery: "Hennig Brand (1669)",
        namedBy: "Hennig Brand (1669)",
        oxidation: "-3, +3, +5",
        electronegativity: "2,19 (Pauling)"
    }
    },
    { n: 16, s: "S", name: "Sulfur", r: 3, c: 16, cat: "nonmetal", config: "[Ne] 3s² 3p⁴", wikiData: {
        appearance: "Rắn, màu vàng",
        mass: "32,06(1)",
        phase: "Chất rắn",
        melting: "388,36 K (115,21 °C)",
        boiling: "717,75 K (444,6 °C)",
        density: "2,07 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-2, +4, +6",
        electronegativity: "2,58 (Pauling)"
    }
    },
    { n: 17, s: "Cl", name: "Chlorine", r: 3, c: 17, cat: "halogen", config: "[Ne] 3s² 3p⁵", wikiData: {
        appearance: "Khí màu vàng lục",
        mass: "35,45(1)",
        phase: "Khí",
        melting: "171,6 K (-101,5 °C)",
        boiling: "239,11 K (-34,04 °C)",
        density: "3,214 g/L (điều kiện tiêu chuẩn)",
        discovery: "Carl Wilhelm Scheele (1774)",
        namedBy: "Carl Wilhelm Scheele (1774)",
        oxidation: "-1, +1, +3, +5, +7",
        electronegativity: "3,16 (Pauling)"
    }
    },
    { n: 18, s: "Ar", name: "Argon", r: 3, c: 18, cat: "noble", config: "[Ne] 3s² 3p⁶", wikiData: {
        appearance: "Khí không màu",
        mass: "39,948(2)",
        phase: "Khí",
        melting: "83,80 K (-189,35 °C)",
        boiling: "87,30 K (-185,85 °C)",
        density: "1,784 g/L (điều kiện tiêu chuẩn)",
        discovery: "Lord Rayleigh & Sir William Ramsay (1894)",
        namedBy: "Lord Rayleigh & Sir William Ramsay (1894)",
        oxidation: "0",
        electronegativity: "0 (Pauling)"
    }
    },
    { n: 19, s: "K", name: "Potassium", r: 4, c: 1, cat: "alkali", config: "[Ar] 4s¹", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "39,0983(1)",
        phase: "Chất rắn",
        melting: "336,53 K (63,38 °C)",
        boiling: "1032 K (759 °C)",
        density: "0,862 g/cm³",
        discovery: "Humphry Davy (1807)",
        namedBy: "Humphry Davy (1807)",
        oxidation: "1",
        electronegativity: "0,82 (Pauling)"
    }
    },
    { n: 20, s: "Ca", name: "Calcium", r: 4, c: 2, cat: "alkaline", config: "[Ar] 4s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "40,078(4)",
        phase: "Chất rắn",
        melting: "1115 K (842 °C)",
        boiling: "1757 K (1484 °C)",
        density: "1,55 g/cm³",
        discovery: "Humphry Davy (1808)",
        namedBy: "Humphry Davy (1808)",
        oxidation: "2",
        electronegativity: "1,00 (Pauling)"
    }
    },
    { n: 21, s: "Sc", name: "Scandium", r: 4, c: 3, cat: "transition", config: "[Ar] 3d¹ 4s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "44,955908(1)",
        phase: "Chất rắn",
        melting: "1814 K (1541 °C)",
        boiling: "3109 K (2836 °C)",
        density: "2,985 g/cm³",
        discovery: "Lars Fredrik Nilson (1879)",
        namedBy: "Lars Fredrik Nilson (1879)",
        oxidation: "3",
        electronegativity: "1,36 (Pauling)"
    }
    },
    { n: 22, s: "Ti", name: "Titanium", r: 4, c: 4, cat: "transition", config: "[Ar] 3d² 4s²", wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "47,867(1)",
        phase: "Chất rắn",
        melting: "1941 K (1668 °C)",
        boiling: "3560 K (3287 °C)",
        density: "4,506 g/cm³",
        discovery: "William Gregor (1791)",
        namedBy: "Martin Heinrich Klaproth (1795)",
        oxidation: "2, 3, 4",
        electronegativity: "1,54 (Pauling)"
    }
    },
    { n: 23, s: "V", name: "Vanadium", r: 4, c: 5, cat: "transition", config: "[Ar] 3d³ 4s²", wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "50,9415(1)",
        phase: "Chất rắn",
        melting: "2183 K (1910 °C)",
        boiling: "3680 K (3407 °C)",
        density: "6,09 g/cm³",
        discovery: "Andrés Manuel del Río (1801)",
        namedBy: "Nils Gabriel Svanberg (1830)",
        oxidation: "-2, -1, +2, +3, +4, +5",
        electronegativity: "1,63 (Pauling)"
    }
    },
    { n: 24, s: "Cr", name: "Chromium", r: 4, c: 6, cat: "transition", config: "[Ar] 3d⁵ 4s¹", wikiData : {
        appearance: "Kim loại màu trắng xám",
        mass: "51,9961(6)",
        phase: "Chất rắn",
        melting: "2180 K (1907 °C)",
        boiling: "2944 K (2671 °C)",
        density: "7,19 g/cm³",
        discovery: "Louis Nicolas Vauquelin (1797)",
        namedBy: "Louis Nicolas Vauquelin (1797)",
        oxidation: "-2, -1, 0, +1, +2, +3, +4, +5, +6",
        electronegativity: "1,66 (Pauling)"
    }},
    { n: 25, s:"Mn", name:"Manganese", r:"4", c:"7", cat:"transition", config:"[Ar] 3d⁵ 4s²",
    wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "54,938045(5)",
        phase: "Chất rắn",
        melting: "1519 K (1246 °C)",
        boiling: "2334 K (2061 °C)",
        density: "7,21 g/cm³",
        discovery: "Carl Wilhelm Scheele (1774)",
        namedBy: "Johann Gottlieb Gahn (1774)",
        oxidation: "-3, -2, -1, 0, +1, +2, +3, +4, +6, +7",
        electronegativity: "1,55 (Pauling)"
    }},
    { n:"26", s:"Fe", name:"Iron", r:"4", c:"8", cat:"transition", config:"[Ar] 3d⁶ 4s²" , wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "55,845(2)",
        phase: "Chất rắn",
        melting: "1811 K (1538 °C)",
        boiling: "3134 K (2862 °C)",
        density: "7,874 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-2, -1, 0, +1, +2, +3, +4, +6",
        electronegativity: "1,83 (Pauling)"
    }},
    { n:"27", s:"Co", name:"Cobalt", r:"4", c:"9", cat:"transition", config:"[Ar] 3d⁷ 4s²" , wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "58,933195(5)",
        phase: "Chất rắn",
        melting: "1768 K (1495 °C)",
        boiling: "3200 K (2927 °C)",
        density: "8,90 g/cm³",
        discovery: "Georg Brandt (1735)",
        namedBy: "Georg Brandt (1735)",
        oxidation: "-3, -2, -1, 0, +1, +2, +3",
        electronegativity: "1,88 (Pauling)"
    }},
    { n:"28", s:"Ni", name:"Nickel", r:"4", c:"10", cat:"transition" , config :"[Ar] 3d⁸ 4s²" , wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "58,6934(4)",
        phase: "Chất rắn",
        melting: "1728 K (1455 °C)",
        boiling: "3186 K (2913 °C)",
        density: "8,908 g/cm³",
        discovery: "Axel Fredrik Cronstedt (1751)",
        namedBy: "Axel Fredrik Cronstedt (1751)",
        oxidation: "-1, 0, +1, +2, +3, +4",
        electronegativity: "1,91 (Pauling)"
    }},
    { n:'29', s:'Cu', name:'Copper', r:'4', c:'11', cat:'transition', config:'[Ar] 3d¹⁰ 4s¹', wikiData: {
        appearance: "Kim loại màu đỏ cam",
        mass: "63,546(3)",
        phase: "Chất rắn",
        melting: "1357,77 K (1084,62 °C)",
        boiling: "2835 K (2562 °C)",
        density: "8,96 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-2, -1, 0, +1, +2",
        electronegativity: "1,90 (Pauling)"
    }},
    { n:'30', s:'Zn', name:'Zinc', r:'4', c:'12', cat:'transition', config:'[Ar] 3d¹⁰ 4s²', wikiData: {
        appearance: "Kim loại màu trắng xám",
        mass: "65,38(2)",
        phase: "Chất rắn",
        melting: "692,68 K (419,53 °C)",
        boiling: "1180 K (907 °C)",
        density: "7,14 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "0, +1, +2",
        electronegativity: "1,65 (Pauling)"
    }},
    { n:'31', s:'Ga', name:'Gallium', r:'4', c:'13', cat:'basic-metal', config:'[Ar] 3d¹⁰ 4s² 4p¹', wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "69,723(1)",
        phase: "Chất rắn",
        melting: "302,91 K (29,76 °C)",
        boiling: "2477 K (2204 °C)",
        density: "5,91 g/cm³",
        discovery: "Paul-Émile Lecoq de Boisbaudran (1875)",
        namedBy: "Paul-Émile Lecoq de Boisbaudran (1875)",
        oxidation: "+1, +3",
        electronegativity: "1,81 (Pauling)"
    }},
    { n: 32, s: "Ge", name: "Germanium", r: 4, c: 14, cat: "semimetal", config: "[Ar] 3d¹⁰ 4s² 4p²", wikiData: {
        appearance: "Rắn, màu xám kim loại",
        mass: "72,63(1)",
        phase: "Chất rắn",
        melting: "1211,40 K (938,25 °C)",
        boiling: "3106 K (2833 °C)",
        density: "5,323 g/cm³",
        discovery: "Clemens Winkler (1886)",
        namedBy: "Clemens Winkler (1886)",
        oxidation: "+2, +4",
        electronegativity: "2,01 (Pauling)"
    }},
    { n: 33, s: "As", name: "Arsenic", r: 4, c: 15, cat: "semimetal", config: "[Ar] 3d¹⁰ 4s² 4p³", wikiData: {
        appearance: "Rắn, màu xám kim loại",
        mass: "74,921595(6)",
        phase: "Chất rắn",
        melting: "1090 K (817 °C)",
        boiling: "887 K (614 °C) (sublimation)",
        density: "5,72 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-3, +3, +5",
        electronegativity: "2,18 (Pauling)"
    }},
    { n: 34, s: "Se", name: "Selenium", r: 4, c: 16, cat: "nonmetal", config: "[Ar] 3d¹⁰ 4s² 4p⁴", wikiData: {
        appearance: "Rắn, có nhiều dạng thù hình: xám kim loại, đỏ sẫm, đen",
        mass: "78,971(8)",
        phase: "Chất rắn",
        melting: "494 K (221 °C)",
        boiling: "958 K (685 °C)",
        density: "4,81 g/cm³ (dạng xám), 4,28 g/cm³ (dạng đỏ)",
        discovery: "Jöns Jacob Berzelius (1817)",
        namedBy: "Jöns Jacob Berzelius (1817)",
        oxidation: "-2, +4, +6",
        electronegativity: "2,55 (Pauling)"
    }},
    { n: 35, s: "Br", name: "Bromine", r: 4, c: 17, cat: "halogen", config: "[Ar] 3d¹⁰ 4s² 4p⁵", wikiData: {
        appearance: "Chất lỏng màu đỏ nâu",
        mass: "79,904(1)",
        phase: "Chất lỏng",
        melting: "265,8 K (-7,2 °C)",
        boiling: "332,0 K (58,8 °C)",
        density: "3,12 g/cm³",
        discovery: "Antoine Jérôme Balard (1826)",
        namedBy: "Antoine Jérôme Balard (1826)",
        oxidation: "-1, +1, +3, +5",
        electronegativity: "2,96 (Pauling)"
    }},
    { n: 36, s: "Kr", name: "Krypton", r: 4, c: 18, cat: "noble", config: "[Ar] 3d¹⁰ 4s² 4p⁶", wikiData: {
        appearance: "Khí không màu",
        mass: "83,798(2)",
        phase: "Chất khí",
        melting: "115,79 K (-157,36 °C)",
        boiling: "119,93 K (-153,22 °C)",
        density: "3,75 g/L (điều kiện tiêu chuẩn)",
        discovery: "William Ramsay và Morris Travers (1898)",
        namedBy: "William Ramsay (1898)",
        oxidation: "0",
        electronegativity: "0 (Pauling)"
    }},

    { n: 37, s: "Rb", name: "Rubidium", r: 5, c: 1, cat: "alkali", config: "[Kr] 5s¹", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "85,4678(3)",
        phase: "Chất rắn",
        melting: "312,46 K (39,31 °C)",
        boiling: "961 K (688 °C)",
        density: "1,532 g/cm³",
        discovery: "Robert Bunsen và Gustav Kirchhoff (1861)",
        namedBy: "Robert Bunsen và Gustav Kirchhoff (1861)",
        oxidation: "1",
        electronegativity: "0,82 (Pauling)"
    }},
    { n: 38, s: "Sr", name: "Strontium", r: 5, c: 2, cat: "alkaline", config: "[Kr] 5s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "87,62(1)",
        phase: "Chất rắn",
        melting: "1050 K (777 °C)",
        boiling: "1650 K (1377 °C)",
        density: "2,64 g/cm³",
        discovery: "Adair Crawford (1790)",
        namedBy: "Adair Crawford (1790)",
        oxidation: "2",
        electronegativity: "0,95 (Pauling)"
    }},
    { n: 39, s: "Y", name: "Yttrium", r: 5, c: 3, cat: "transition", config: "[Kr] 4d¹ 5s²" , wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "88,90584(2)",
        phase: "Chất rắn",
        melting: "1799 K (1526 °C)",
        boiling: "3203 K (2930 °C)",
        density: "4,47 g/cm³",
        discovery: "Jöns Jacob Berzelius (1828)",
        namedBy: "Jöns Jacob Berzelius (1828)",
        oxidation: "3",
        electronegativity: "1,22 (Pauling)"
    }},
    { n: 40, s: "Zr", name: "Zirconium", r: 5, c: 4, cat: "transition", config: "[Kr] 4d² 5s²", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "91,224(2)",
        phase: "Chất rắn",
        melting: "2125 K (1852 °C)",
        boiling: "4650 K (4377 °C)",
        density: "6,52 g/cm³",
        discovery: "Martin Heinrich Klaproth (1789)",
        namedBy: "Martin Heinrich Klaproth (1789)",
        oxidation: "4",
        electronegativity: "1,33 (Pauling)"
    }},
    { n: 41, s: "Nb", name: "Niobium", r: 5, c: 5, cat: "transition", config: "[Kr] 4d⁴ 5s¹", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "92,90637(2)",
        phase: "Chất rắn",
        melting: "2750 K (2477 °C)",
        boiling: "5017 K (4744 °C)",
        density: "8,57 g/cm³",
        discovery: "Charles Hatchett (1801)",
        namedBy: "Charles Hatchett (1801)",
        oxidation: "5",
        electronegativity: "1,6 (Pauling)"
    }},
    { n: 42, s: "Mo", name: "Molybdenum", r: 5, c: 6, cat: "transition", config: "[Kr] 4d⁵ 5s¹", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "95,95(1)",
        phase: "Chất rắn",
        melting: "2896 K (2623 °C)",
        boiling: "4912 K (4639 °C)",
        density: "10,2 g/cm³",
        discovery: "Carl Wilhelm Scheele (1778)",
        namedBy: "Carl Wilhelm Scheele (1778)",
        oxidation: "6",
        electronegativity: "2,16 (Pauling)"
    }},
    { n: 43, s: "Tc", name: "Technetium", r: 5, c: 7, cat: "transition", config: "[Kr] 4d⁵ 5s²", wikiData : {
        appearance:"Kim loại mềm màu trắng xám",
        mass:"98(1)",
        phase:"Chất rắn",
        melting:"2430 K (2157 °C)",
        boiling:"4538 K (4265 °C)",
        density:"11 g/cm³",
        discovery:"Emilio Segrè và Carlo Perrier (1937)",
        namedBy:"Emilio Segrè và Carlo Perrier (1937)",
        oxidation:"+7",
        electronegativity:"1,9"
    }},
    { n: 44, s: "Ru", name: "Ruthenium", r: 5, c: 8, cat:"transition", config:"[Kr] 4d⁷ 5s¹", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "101,07(2)",
        phase: "Chất rắn",
        melting: "2607 K (2334 °C)",
        boiling: "4423 K (4150 °C)",
        density: "12,45 g/cm³",
        discovery: "Karl Ernst Claus (1844)",
        namedBy: "Karl Ernst Claus (1844)",
        oxidation: "+3, +4, +8",
        electronegativity: "2,2 (Pauling)"
    }},
    { n: 45, s:"Rh", name:"Rhodium", r : 5 , c : 9 , cat :"transition" , config : "[Kr] 4d⁸ 5s¹", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "102,90550(2)",
        phase: "Chất rắn",
        melting: "2237 K (1964 °C)",
        boiling: "3968 K (3695 °C)",
        density: "12,41 g/cm³",
        discovery: "William Hyde Wollaston (1803)",
        namedBy: "William Hyde Wollaston (1803)",
        oxidation: "+3",
        electronegativity: "2,28 (Pauling)"
    }},
    { n : 46 , s : 'Pd' , name : 'Palladium' , r : 5 , c : 10 , cat : 'transition' , config : '[Kr] 4d¹⁰', wikiData: {
        appearance: "Kim loại mềm, màu trắng xám",
        mass: "106,42(1)",
        phase: "Chất rắn",
        melting: "1828 K (1555 °C)",
        boiling: "3236 K (2963 °C)",
        density: "12,02 g/cm³",
        discovery: "William Hyde Wollaston (1803)",
        namedBy: "William Hyde Wollaston (1803)",
        oxidation: "+2, +4",
        electronegativity: "2,20 (Pauling)"
    }},
    { n : 47 , s : 'Ag' , name : 'Silver' , r : 5 , c : 11 , cat : 'transition' , config : '[Kr] 4d¹⁰ 5s¹', wikiData: {
        appearance:"Kim loại mềm, màu trắng sáng",
        mass:"107,8682(2)",
        phase:"Chất rắn",
        melting:"1234,93 K (961,78 °C)",
        boiling:"2435 K (2162 °C)",
        density:"10,49 g/cm³",
        discovery:"Người xưa cổ đại",
        namedBy:"Người xưa cổ đại",
        oxidation:"+1,+2,+3",
        electronegativity:"1,93 (Pauling)"
    }},
    { n : 48 , s : 'Cd' , name : 'Cadmium' , r : 5 , c : 12 , cat :'transition', config:'[Kr] 4d¹⁰ 5s²', wikiData:{
      appearance:"Kim loại mềm màu trắng xám",
      mass:"112,414(4)",
      phase:"Chất rắn",
      melting:"594,2 K (321 °C)",
      boiling:"1040 K (767 °C)",
      density:"8.65 g/cm³",
      discovery:"Karl Samuel Leberecht Hermann và Friedrich Stromeyer (1817)",
      namedBy:"Karl Samuel Leberecht Hermann và Friedrich Stromeyer (1817)", 
      oxidation:"+2", 
      electronegativity:"1.69"
    }},
    { n : 49 , s :'In', name:'Indium', r:'5', c:'13', cat:'basic-metal', config:'[Kr] 4d¹⁰ 5s²', wikiData: {
        appearance:"Kim loại mềm màu bạc sáng",
        mass:"114,818(3)",
        phase:"Chất rắn",
        melting:"429,75 K (156,6 °C)",
        boiling:"2345 K (2072 °C)",
        density:"7,31 g/cm³",
        discovery:"Ferdinand Reich và Hieronymous Theodor Richter (1863)",
        namedBy:"Ferdinand Reich và Hieronymous Theodor Richter (1863)",
        oxidation:"+1, +3",
        electronegativity:"1,78 (Pauling)"
    }},
    { n: 50, s: "Sn", name: "Tin", r: 5, c: 14, cat: "basic-metal", config: "[Kr] 4d¹⁰ 5s² 5p²", wikiData: {
        appearance: "Kim loại mềm, màu trắng xám",
        mass: "118,710(7)",
        phase: "Chất rắn",
        melting: "505,08 K (231,93 °C)",
        boiling: "2875 K (2602 °C)",
        density: "7,31 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-4, +2, +4",
        electronegativity: "1,96 (Pauling)"
    }},
    { n: 51, s: "Sb", name: "Antimony", r: 5, c: 15, cat: "semimetal", config: "[Kr] 4d¹⁰ 5s² 5p³" , wikiData: {
        appearance: "Rắn, màu xám kim loại",
        mass: "121,760(1)",
        phase: "Chất rắn",
        melting: "903,78 K (630,63 °C)",
        boiling: "1860 K (1587 °C)",
        density: "6,697 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-3, +3, +5",
        electronegativity: "2,05 (Pauling)"
    }},
    { n: 52, s: "Te", name: "Tellurium", r: 5, c: 16, cat: "semimetal", config: "[Kr] 4d¹⁰ 5s² 5p⁴" , wikiData: {
        appearance: "Rắn, màu xám kim loại",
        mass: "127,60(3)",
        phase: "Chất rắn",
        melting: "722,66 K (449,51 °C)",
        boiling: "1261 K (988 °C)",
        density: "6,24 g/cm³",
        discovery: "Franz-Joseph Müller von Reichenstein (1782)",
        namedBy: "Franz-Joseph Müller von Reichenstein (1782)",
        oxidation: "-2, +2, +4, +6",
        electronegativity: "2,1 (Pauling)"
    }},
    { n: 53, s: "I", name: "Iodine", r: 5, c: 17, cat: "halogen", config: "[Kr] 4d¹⁰ 5s² 5p⁵", wikiData: {
        appearance: "Rắn, màu đen tím",
        mass: "126,90447(3)",
        phase: "Chất rắn",
        melting: "386,85 K (113,7 °C)",
        boiling: "457,4 K (184,3 °C)",
        density: "4,933 g/cm³",
        discovery: "Bernard Courtois (1811)",
        namedBy: "Joseph Louis Gay-Lussac (1813)",
        oxidation: "-1, +1, +3, +5",
        electronegativity: "2,66 (Pauling)"
    }},
    { n: 54, s: "Xe", name: "Xenon", r: 5, c: 18, cat: "noble", config: "[Kr] 4d¹⁰ 5s² 5p⁶", wikiData: {
        appearance: "Khí không màu",
        mass: "131,293(6)",
        phase: "Chất khí",
        melting: "161,4 K (-111,75 °C)",
        boiling: "165,03 K (-108,12 °C)",
        density: "5,894 g/L (điều kiện tiêu chuẩn)",
        discovery: "William Ramsay và Morris Travers (1898)",
        namedBy: "William Ramsay (1898)",
        oxidation: "0, +2, +4, +6, +8",
        electronegativity: "2,60 (Pauling)"
    }},

    { n: 55, s: "Cs", name: "Cesium", r: 6, c: 1, cat: "alkali", config: "[Xe] 6s¹" , wikiData: {
        appearance: "Kim loại mềm, màu vàng nhạt",
        mass: "132,90545196(6)",
        phase: "Chất rắn",
        melting: "301,59 K (28,44 °C)",
        boiling: "944 K (671 °C)",
        density: "1,93 g/cm³",
        discovery: "Robert Bunsen và Gustav Kirchhoff (1860)",
        namedBy: "Robert Bunsen và Gustav Kirchhoff (1860)",
        oxidation: "1",
        electronegativity: "0,79 (Pauling)"
    }},
    { n: 56, s: "Ba", name: "Barium", r: 6, c: 2, cat: "alkaline", config: "[Xe] 6s²" , wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "137,327(7)",
        phase: "Chất rắn",
        melting: "1000 K (727 °C)",
        boiling: "2118 K (1845 °C)",
        density: "3,62 g/cm³",
        discovery: "Carl Wilhelm Scheele (1772)",
        namedBy: "Carl Wilhelm Scheele (1772)",
        oxidation: "2",
        electronegativity: "0,89 (Pauling)"
    }},
    { n: "57 - 71", s: "", name: "Lanthanides", r: 6, c: 3, cat: "lanthanide", config: "[Xe] 5d¹ 6s²  [Xe] 4f¹⁴ 5d¹ 6s²"},
    { n: 57, s: "La", name: "Lanthanum", r: 9, c: 4, cat: "lanthanide", config: "[Xe] 5d¹ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "138,90547(7)",
        phase: "Chất rắn",
        melting: "1193 K (920 °C)",
        boiling: "3737 K (3464 °C)",
        density: "6,15 g/cm³",
        discovery: "Carl Gustaf Mosander (1839)",
        namedBy: "Carl Gustaf Mosander (1839)",
        oxidation: "+3",
        electronegativity: "1,1 (Pauling)"
    }},
    { n: 58, s: "Ce", name: "Cerium", r: 9, c: 5, cat: "lanthanide", config: "[Xe] 4f¹ 5d¹ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "140,116(1)",
        phase: "Chất rắn",
        melting: "1068 K (795 °C)",
        boiling: "3716 K (3443 °C)",
        density: "6,77 g/cm³",
        discovery: "Martin Heinrich Klaproth (1803)",
        namedBy: "Martin Heinrich Klaproth (1803)",
        oxidation: "+3, +4",
        electronegativity: "1,12 (Pauling)"
    }},
    { n: 59, s: "Pr", name: "Praseodymium", r: 9, c: 6, cat: "lanthanide", config: "[Xe] 4f³ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "140,90765(2)",
        phase: "Chất rắn",
        melting: "1204 K (935 °C)",
        boiling: "3403 K (3130 °C)",
        density: "6,77 g/cm³",
        discovery: "Carl Auer von Welsbach (1885)",
        namedBy: "Carl Auer von Welsbach (1885)",
        oxidation: "+3",
        electronegativity: "1,13 (Pauling)"
    }},
    { n: 60, s: "Nd", name: "Neodymium", r: 9, c: 7, cat: "lanthanide", config: "[Xe] 4f⁴ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "144,242(3)",
        phase: "Chất rắn",
        melting: "1297 K (1024 °C)",
        boiling: "3347 K (3074 °C)",
        density: "7,01 g/cm³",
        discovery: "Carl Auer von Welsbach (1885)",
        namedBy: "Carl Auer von Welsbach (1885)",
        oxidation: "+3",
        electronegativity: "1,14 (Pauling)"
    }},
    { n: 61, s: "Pm", name: "Promethium", r: 9, c: 8, cat: "lanthanide", config: "[Xe] 4f⁵ 6s²", wikiData : {
        appearance:"Kim loại mềm, màu bạc sáng",
        mass:"145(1)",
        phase:"Chất rắn",
        melting:"1315 K (1042 °C)",
        boiling:"3273 K (3000 °C)",
        density:"7,26 g/cm³",
        discovery:"Jacob A. Marinsky, Lawrence E. Glendenin và Charles D. Coryell (1945)",
        namedBy:"Jacob A. Marinsky, Lawrence E. Glendenin và Charles D. Coryell (1945)",
        oxidation:"+3",
        electronegativity:"1,13 (Pauling)"
    }},
    { n: 62, s: "Sm", name: "Samarium", r: 9, c: 9, cat:"lanthanide", config:"[Xe] 4f⁶ 6s²" , wikiData:{
      appearance:"Kim loại cứng, màu bạc sáng",
      mass:"150.36(2)",
      phase:"Chất rắn",
      melting:"1345 K (1072 °C)",
      boiling:"2173 K (1900 °C)",
      density:"7.52 g/cm³",
      discovery:"Lecoq de Boisbaudran (1879)",
      namedBy:"Lecoq de Boisbaudran (1879)",
      oxidation:"+2,+3",
      electronegativity:"1.17 (Pauling)"
    }},
    { n: 63, s: "Eu", name: "Europium", r: 9, c: 10, cat: "lanthanide", config: "[Xe] 4f⁷ 6s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "151,964(1)",
        phase: "Chất rắn",
        melting: "1099 K (826 °C)",
        boiling: "1802 K (1529 °C)",
        density: "5,24 g/cm³",
        discovery: "Eugène-Anatole Demarçay (1901)",
        namedBy: "Eugène-Anatole Demarçay (1901)",
        oxidation: "+2, +3",
        electronegativity: "1,2 (Pauling)"
    }},
    { n: 64, s: "Gd", name: "Gadolinium", r: 9, c: 11, cat: "lanthanide", config: "[Xe] 4f⁷ 5d¹ 6s²" , wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "157,25(3)",
        phase: "Chất rắn",
        melting: "1585 K (1312 °C)",
        boiling: "3546 K (3273 °C)",
        density: "7,90 g/cm³",
        discovery: "Jean Charles Galissard de Marignac (1880)",
        namedBy: "Jean Charles Galissard de Marignac (1880)",
        oxidation: "+3",
        electronegativity: "1,20 (Pauling)"
    }},
    { n: 65, s: "Tb", name: "Terbium", r: 9, c: 12, cat: "lanthanide", config: "[Xe] 4f⁹ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "158,92535(2)",
        phase: "Chất rắn",
        melting: "1629 K (1356 °C)",
        boiling: "3396 K (3123 °C)",
        density: "8,23 g/cm³",
        discovery: "Carl Gustaf Mosander (1843)",
        namedBy: "Carl Gustaf Mosander (1843)",
        oxidation: "+3",
        electronegativity: "1,2 (Pauling)"
    }},
    { n: 66, s: "Dy", name: "Dysprosium", r: 9, c: 13, cat: "lanthanide", config: "[Xe] 4f¹⁰ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "162,500(1)",
        phase: "Chất rắn",
        melting: "1680 K (1407 °C)",
        boiling: "2840 K (2567 °C)",
        density: "8,55 g/cm³",
        discovery: "Paul-Émile Lecoq de Boisbaudran (1886)",
        namedBy: "Paul-Émile Lecoq de Boisbaudran (1886)",
        oxidation: "+3",
        electronegativity: "1,22 (Pauling)"
    }},
    { n: 67, s: "Ho", name: "Holmium", r: 9, c: 14, cat: "lanthanide", config: "[Xe] 4f¹¹ 6s²", wikiData: { 
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "164,93033(2)",
        phase: "Chất rắn",
        melting: "1734 K (1461 °C)",
        boiling: "2873 K (2600 °C)",
        density: "8,79 g/cm³",
        discovery: "Marc Delafontaine và Jacques-Louis Soret (1878)",
        namedBy: "Marc Delafontaine và Jacques-Louis Soret (1878)",
        oxidation: "+3",
        electronegativity: "1,23 (Pauling)"
    }},
    { n: 68, s: "Er", name: "Erbium", r: 9, c: 15, cat: "lanthanide", config: "[Xe] 4f¹² 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "167,259(3)",
        phase: "Chất rắn",
        melting: "1802 K (1529 °C)",
        boiling: "3141 K (2868 °C)",
        density: "9,07 g/cm³",
        discovery: "Carl Gustaf Mosander (1843)",
        namedBy: "Carl Gustaf Mosander (1843)",
        oxidation: "+3",
        electronegativity: "1,24 (Pauling)"
    }},
    { n: 69, s: "Tm", name: "Thulium", r: 9, c: 16, cat: "lanthanide", config: "[Xe] 4f¹³ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "168,93422(2)",
        phase: "Chất rắn",
        melting: "1818 K (1545 °C)",
        boiling: "2223 K (1950 °C)",
        density: "9,32 g/cm³",
        discovery: "Per Teodor Cleve (1879)",
        namedBy: "Per Teodor Cleve (1879)",
        oxidation: "+3",
        electronegativity: "1,25 (Pauling)"
    }},
    { n: 70, s: "Yb", name: "Ytterbium", r: 9, c: 17, cat: "lanthanide", config: "[Xe] 4f¹⁴ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "173,045(1)",
        phase: "Chất rắn",
        melting: "1097 K (824 °C)",
        boiling: "1469 K (1196 °C)",
        density: "6,97 g/cm³",
        discovery: "Jean Charles Galissard de Marignac (1878)",
        namedBy: "Jean Charles Galissard de Marignac (1878)",
        oxidation: "+3",
        electronegativity: "1,27 (Pauling)"
    }},
    { n: 71, s: "Lu", name: "Lutetium", r: 9, c: 18, cat: "lanthanide", config: "[Xe] 4f¹⁴ 5d¹ 6s²", wikiData : {
        appearance:"Kim loại cứng, màu bạc sáng",
        mass:"174.9668(2)",
        phase:"Chất rắn",
        melting:"1925 K (1652 °C)",
        boiling:"3675 K (3402 °C)",
        density:"9.84 g/cm³",
        discovery:"Carl Auer von Welsbach và Georges Urbain (1907)",
        namedBy:"Carl Auer von Welsbach và Georges Urbain (1907)",
        oxidation:"+3",
        electronegativity:"1,27 (Pauling)"
    }},

    { n: 72, s: "Hf", name: "Hafnium", r: 6, c: 4, cat: "transition", config: "[Xe] 4f¹⁴ 5d² 6s²", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "178,49(2)",
        phase: "Chất rắn",
        melting: "2506 K (2233 °C)",
        boiling: "4876 K (4603 °C)",
        density: "13,31 g/cm³",
        discovery: "Dirk Coster và George de Hevesy (1923)",
        namedBy: "Dirk Coster và George de Hevesy (1923)",
        oxidation: "+4",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 73, s: "Ta", name: "Tantalum", r: 6, c: 5, cat: "transition", config: "[Xe] 4f¹⁴ 5d³ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "180,9479(1)",
        phase: "Chất rắn",
        melting: "3290 K (3017 °C)",
        boiling: "5731 K (5458 °C)",
        density: "16,69 g/cm³",
        discovery: "Anders Gustaf Ekeberg (1802)",
        namedBy: "Anders Gustaf Ekeberg (1802)",
        oxidation: "+5",
        electronegativity: "1,5 (Pauling)"
    }},
    { n: 74, s: "W", name: "Tungsten", r: 6, c: 6, cat: "transition", config: "[Xe] 4f¹⁴ 5d⁴ 6s²", wikiData: {
        appearance: "Kim loại cứng, màu trắng xám",
        mass: "183,84(1)",
        phase: "Chất rắn",
        melting: "3695 K (3422 °C)",
        boiling: "6203 K (5930 °C)",
        density: "19,25 g/cm³",
        discovery: "Carl Wilhelm Scheele (1783)",
        namedBy:"Carl Wilhelm Scheele (1783)",
        oxidation:"+6",
        electronegativity:"1,7 (Pauling)"
    }},
    { n: 75, s: "Re", name: "Rhenium", r: 6, c: 7, cat: "transition", config: "[Xe] 4f¹⁴ 5d⁵ 6s²", wikiData : {
        appearance:"Kim loại cứng, màu trắng xám",
        mass:"186.207(1)",
        phase:"Chất rắn",
        melting:"3459 K (3186 °C)",
        boiling:"5903 K (5630 °C)",
        density:"21.02 g/cm³",
        discovery:"Wolfgang von Osten và Masataka Ogawa (1925)",
        namedBy:"Wolfgang von Osten và Masataka Ogawa (1925)",
        oxidation:"+7",
        electronegativity:"1,9 (Pauling)"
    }},
    { n: 76, s: "Os", name: "Osmium", r: 6, c: 8, cat: "transition", config : "[Xe] 4f¹⁴ 5d⁶ 6s²", wikiData : {
      appearance:"Kim loại cứng và nặng màu trắng xám",
      mass:"190.23(1) u",
      phase:"Chất rắn",
      melting:"3306 K (3033 °C)",
      boiling:"5281 K (5012 °C)", 
      density:"22.59 g/cm³",
      discovery:"Smithson Tennant và William Hyde Wollaston (1803)", 
      namedBy:"Smithson Tennant và William Hyde Wollaston (1803)", 
      oxidation:"+4,+2,+3,+4,+6,+8",
      electronegativity:"2.2 (Pauling)"
    }},
    { n: 77, s: "Ir", name: "Iridium", r: 6, c: 9, cat: "transition", config: "[Xe] 4f¹⁴ 5d⁷ 6s²", wikiData : {
        appearance:"Kim loại cứng, màu trắng xám",
        mass:"192.217(3)",
        phase:"Chất rắn",
        melting:"2719 K (2446 °C)",
        boiling:"4403 K (4130 °C)",
        density:"22.56 g/cm³",
        discovery:"Smithson Tennant và William Hyde Wollaston (1803)",
        namedBy:"Smithson Tennant và William Hyde Wollaston (1803)",
        oxidation:"+4,+3,+2,+1",
        electronegativity:"2,2 (Pauling)"
    }},
    { n: 78, s: "Pt", name: "Platinum", r: 6, c: 10, cat: "transition", config: "[Xe] 4f¹⁴ 5d⁹ 6s¹", wikiData: {
        appearance:"Kim loại mềm, màu trắng xám",
        mass:"195.084(9)",
        phase:"Chất rắn",
        melting:"2041.4 K (1768.2 °C)",
        boiling:"4098 K (3825 °C)",
        density:"21.45 g/cm³",
        discovery:"Antonio de Ulloa (1735)",
        namedBy:"Antonio de Ulloa (1735)",
        oxidation:"+2, +4, +6",
        electronegativity:"2,28 (Pauling)"
    }},
    { n: 79, s: "Au", name: "Gold", r: 6, c: 11, cat: "transition", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", wikiData: {
        appearance:"Kim loại mềm, màu vàng",
        mass:"196.966569(4)",
        phase:"Chất rắn",
        melting:"1337.33 K (1064.18 °C)",
        boiling:"3243 K (2970 °C)",
        density:"19.3 g/cm³",
        discovery:"Người xưa (trước công nguyên)",
        namedBy:"Người xưa (trước công nguyên)",
        oxidation:"+1, +3",
        electronegativity:"2,54 (Pauling)"
    }},
    { n: 80, s: "Hg", name: "Mercury", r: 6, c: 12, cat: "transition", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", wikiData: {
        appearance:"Kim loại lỏng, màu trắng xám",
        mass:"200.59(2) u",
        phase:"Chất lỏng",
        melting:"234.32 K (-38.83 °C)",
        boiling:"629.88 K (356.73 °C)",
        density:"13.534 g/cm³",
        discovery:"Người xưa (trước công nguyên)",
        namedBy:"Người xưa (trước công nguyên)",
        oxidation:"+2,+1",
        electronegativity:"2,00 (Pauling)"
    }},
    { n: 81, s: "Tl", name: "Thallium", r: 6, c: 13, cat: "basic-metal", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", wikiData: {
        appearance: "Kim loại mềm, màu trắng xám",
        mass: "204,38(1)",
        phase: "Chất rắn",
        melting: "577 K (304 °C)",
        boiling: "1746 K (1473 °C)",
        density: "11,85 g/cm³",
        discovery: "William Crookes (1861)",
        namedBy: "William Crookes (1861)",
        oxidation: "+1, +3",
        electronegativity: "1,62 (Pauling)"
    }},
    { n: 82, s: "Pb", name: "Lead", r: 6, c: 14, cat: "basic-metal", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", wikiData: {
        appearance: "Kim loại mềm, màu xám chì",
        mass: "207,2(1)",
        phase: "Chất rắn",
        melting: "600,61 K (327,46 °C)",
        boiling: "2022 K (1749 °C)",
        density: "11,34 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "-4, +2, +4",
        electronegativity: "2,33 (Pauling)"
    }},
    { n: 83, s: "Bi", name: "Bismuth", r: 6, c: 15, cat: "basic-metal", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³" , wikiData: {
        appearance: "Kim loại cứng, màu trắng xám với ánh hồng",
        mass: "208,98040(1)",
        phase: "Chất rắn",
        melting: "544,7 K (271,5 °C)",
        boiling: "1837 K (1564 °C)",
        density: "9,78 g/cm³",
        discovery: "Được biết từ thời cổ đại",
        namedBy: "Không rõ",
        oxidation: "+3, +5",
        electronegativity: "2,02 (Pauling)"
    }},
    { n: 84, s: "Po", name: "Polonium", r: 6, c: 16, cat: "basic-metal", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "209(1)",
        phase: "Chất rắn",
        melting: "527 K (254 °C)",
        boiling: "1235 K (962 °C)",
        density: "9,32 g/cm³",
        discovery: "Marie Curie (1898)",
        namedBy: "Marie Curie (1898)",
        oxidation: "+2, +4, +6",
        electronegativity: "2,0 (Pauling)"
    }},
    { n: 85, s: "At", name: "Astatine", r: 6, c: 17, cat: "halogen", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵" , wikiData: {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "210(2)",
        phase: "Chất rắn",
        melting: "575 K (302 °C) (ước tính)",
        boiling: "610 K (337 °C) (ước tính)",
        density: "7 g/cm³ (ước tính)",
        discovery: "Dmitri Mendeleev (1869) - dự đoán, Dale R. Corson, Kenneth Ross MacKenzie và Emilio Segrè (1940) - phát hiện",
        namedBy: "Dmitri Mendeleev (1869) - dự đoán, Dale R. Corson, Kenneth Ross MacKenzie và Emilio Segrè (1940) - phát hiện",
        oxidation: "-1, +1, +3, +5, +7",
        electronegativity: "2,2 (Pauling)"
    }},
    { n: 86, s: "Rn", name: "Radon", r: 6, c: 18, cat: "noble", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", wikiData: {
        appearance: "Khí không màu",
        mass: "222(1)",
        phase: "Chất khí",
        melting: "202 K (-71 °C)",
        boiling: "211,5 K (-61,6 °C)",
        density: "9,73 g/L (điều kiện tiêu chuẩn)",
        discovery: "Friedrich Ernst Dorn (1900)",
        namedBy: "Friedrich Ernst Dorn (1900)",
        oxidation: "0, +2, +4, +6",
        electronegativity: "2,2 (Pauling)"
    }},

    { n: 87, s: "Fr", name: "Francium", r: 7, c: 1, cat: "alkali", config: "[Rn] 7s¹" , wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng (ước tính)",
        mass: "223(1)",
        phase: "Chất rắn",
        melting: "300 K (27 °C) (ước tính)",
        boiling: "950 K (677 °C) (ước tính)",
        density: "1,87 g/cm³ (ước tính)",
        discovery: "Marguerite Perey (1939)",
        namedBy: "Marguerite Perey (1939)",
        oxidation: "+1",
        electronegativity: "0,7 (Pauling) (ước tính)"
    }},
    { n: 88, s: "Ra", name: "Radium", r: 7, c: 2, cat: "alkaline", config: "[Rn] 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "226(1)",
        phase: "Chất rắn",
        melting: "973 K (700 °C)",
        boiling: "2010 K (1737 °C)",
        density: "5,5 g/cm³",
        discovery: "Marie Curie và Pierre Curie (1898)",
        namedBy: "Marie Curie và Pierre Curie (1898)",
        oxidation: "+2",
        electronegativity: "0,9 (Pauling)"
    }},
    { n: "89 - 103", s: "", name: "Actinides", r: 7, c: 3, cat: "actinide", config: "[Rn] 6d¹ 7s² - [Rn] 5f¹⁴ 7s² 7p¹", },
    { n: 89, s: "Ac", name: "Actinium", r: 10, c: 4, cat: "actinide", config: "[Rn] 6d¹ 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "227(1)",
        phase: "Chất rắn",
        melting: "1500 K (1227 °C)",
        boiling: "3500 ± 300 K (3200 ± 300 °C)",
        density: "10,07 g/cm³",
        discovery: "Friedrich Oskar Giesel (1902)",
        namedBy: "Friedrich Oskar Giesel (1902)",
        oxidation: "+3",
        electronegativity: "1,1 (Pauling)"
    }},
    { n: 90, s: "Th", name: "Thorium", r: 10, c: 5, cat: "actinide", config: "[Rn] 6d² 7s²", wikiData: {
        appearance: "Kim loại cứng, màu bạc sáng",
        mass: "232,0377(4)",
        phase: "Chất rắn",
        melting: "2023 K (1750 °C)",
        boiling: "5061 K (4788 °C)",
        density: "11,72 g/cm³",
        discovery: "Jöns Jakob Berzelius (1828)",
        namedBy: "Jöns Jakob Berzelius (1828)",
        oxidation: "+4",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 91, s: "Pa", name: "Protactinium", r: 10, c: 6, cat: "actinide", config: "[Rn] 5f² 6d¹ 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "231,03588(2)",
        phase: "Chất rắn",
        melting: "1841 K (1568 °C)",
        boiling: "4300 K (4027 °C)",
        density: "15,37 g/cm³",
        discovery: "William Crookes (1885)",
        namedBy: "William Crookes (1885)",
        oxidation: "+5",
        electronegativity: "1,5 (Pauling)"
    }},
    { n: 92, s: "U", name: "Uranium", r: 10, c: 7, cat: "actinide", config: "[Rn] 5f³ 6d¹ 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "238,02891(3)",
        phase: "Chất rắn",
        melting: "1405 K (1132 °C)",
        boiling: "4404 K (4131 °C)",
        density: "19,05 g/cm³",
        discovery: "Martin Heinrich Klaproth (1789)",
        namedBy: "Martin Heinrich Klaproth (1789)",
        oxidation: "+6",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 93, s: "Np", name: "Neptunium", r: 10, c: 8, cat: "actinide", config: "[Rn] 5f⁴ 6d¹ 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "237(1)",
        phase: "Chất rắn",
        melting: "912 K (639 °C)",
        boiling: "4447 K (4174 °C)",
        density: "20,45 g/cm³",
        discovery: "Edwin McMillan và Philip H. Abelson (1940)",
        namedBy: "Edwin McMillan và Philip H. Abelson (1940)",
        oxidation: "+5",
        electronegativity: "1,36 (Pauling)"
    }},
    { n: 94, s: "Pu", name: "Plutonium", r: 10, c: 9, cat: "actinide", config: "[Rn] 5f⁶ 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "244(1)",
        phase: "Chất rắn",
        melting: "912 K (639 °C)",
        boiling: "3505 K (3232 °C)",
        density: "19,82 g/cm³",
        discovery: "Glenn T. Seaborg, Edwin McMillan, J. W. Kennedy và A. C. Wahl (1940)",
        namedBy: "Glenn T. Seaborg, Edwin McMillan, J. W. Kennedy và A. C. Wahl (1940)",
        oxidation: "+4",
        electronegativity: "1,28 (Pauling)"
    }},
    { n: 95, s: "Am", name: "Americium", r: 10, c: 10, cat: "actinide", config: "[Rn] 5f⁷ 7s²", wikiData: {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "243(1)",
        phase: "Chất rắn",
        melting: "1449 K (1176 °C)",
        boiling: "2880 K (2607 °C)",
        density: "13,67 g/cm³",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1945)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1945)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 96, s: "Cm", name: "Curium", r: 10, c: 11, cat: "actinide", config: "[Rn] 5f⁷ 6d¹ 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "247(1)",
        phase: "Chất rắn",
        melting: "1613 K (1340 °C)",
        boiling: "3383 K (3110 °C)",
        density: "13,51 g/cm³",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1944)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1944)",
        oxidation: "+3, +4",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 97, s:"Bk", name:"Berkelium", r:"10", c:"12", cat:"actinide", config:"[Rn] 5f⁹ 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "247(1)",
        phase: "Chất rắn",
        melting: "1259 K (986 °C)",
        boiling: "2900 K (2627 °C)",
        density: "14,78 g/cm³",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1949)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1949)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 98, s:"Cf", name:"Californium", r:"10", c:"13", cat:"actinide", config:"[Rn] 5f¹⁰ 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "251(1)",
        phase: "Chất rắn",
        melting: "1173 K (900 °C)",
        boiling: "1743 K (1470 °C)",
        density: "15,1 g/cm³",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1949)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1949)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 99, s:"Es", name:"Einsteinium", r:"10", c:"14", cat:"actinide", config:"[Rn] 5f¹¹ 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "252(1)",
        phase: "Chất rắn",
        melting: "1133 K (860 °C)",
        boiling: "1269 K (996 °C)",
        density: "8,84 g/cm³",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1952)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1952)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 100, s:"Fm", name:"Fermium", r:"10", c:"15", cat:"actinide", config:"[Rn] 5f¹² 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "257(1)",
        phase: "Chất rắn",
        melting: "1800 K (1500 °C) (ước tính)",
        boiling: "unknown",
        density: "9,7 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1952)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1952)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n: 101, s:"Md", name:"Mendelevium ", r:"10 ", c :"16 ", cat :"actinide ", config :"[Rn] 5f¹³ 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "258(1)",
        phase: "Chất rắn",
        melting: "1100 K (827 °C) (ước tính)",
        boiling: "unknown",
        density: "9,9 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1955)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1955)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n : 102 , s :"No" , name :"Nobelium" , r :"10" , c :"17" , cat :"actinide" , config :"[Rn] 5f¹⁴ 7s²", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "259(1)",
        phase: "Chất rắn",
        melting: "1100 K (827 °C) (ước tính)",
        boiling: "unknown",
        density: "9,9 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1957)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1957)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},
    { n : 103 , s :"Lr" , name :"Lawrencium" , r :"10" , c :"18" , cat :"actinide" , config :"[Rn] 5f¹⁴ 7s² 7p¹", wikiData : {
        appearance: "Kim loại mềm, màu bạc sáng",
        mass: "266(1)",
        phase: "Chất rắn",
        melting: "1900 K (1627 °C) (ước tính)",
        boiling: "unknown",
        density: "14,4 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg và Albert Ghiorso (1961)",
        namedBy: "Glenn T. Seaborg và Albert Ghiorso (1961)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling)"
    }},

    { n: 104, s: "Rf", name: "Rutherfordium", r: 7, c: 4, cat: "transition", config: "[Rn] 5f¹⁴ 6d² 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "267(1)",
        phase: "Chất rắn",
        melting: "2400 K (2127 °C) (ước tính)",
        boiling: "5800 K (5527 °C) (ước tính)",
        density: "17 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1964)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1964)",
        oxidation: "+4",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 105, s: "Db", name: "Dubnium", r: 7, c: 5, cat: "transition", config: "[Rn] 5f¹⁴ 6d³ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "268(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "21,6 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1967)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1967)",
        oxidation: "+5",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 106, s: "Sg", name: "Seaborgium", r: 7, c: 6, cat: "transition", config: "[Rn] 5f¹⁴ 6d⁴ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "269(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "23 - 24 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1974)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1974)",
        oxidation: "+6",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 107, s: "Bh", name: "Bohrium", r: 7, c: 7, cat: "transition", config: "[Rn] 5f¹⁴ 6d⁵ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "270(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "26 - 27 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1981)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1981)",
        oxidation: "+7",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 108, s: "Hs", name: "Hassium", r: 7, c: 8, cat: "transition", config: "[Rn] 5f¹⁴ 6d⁶ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "269(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "27 - 29 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1984)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1984)",
        oxidation: "+8",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 109, s: "Mt", name: "Meitnerium", r: 7, c: 9, cat: "transition", config: "[Rn] 5f¹⁴ 6d⁷ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "278(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "unknown",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1982)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1982)",
        oxidation: "+9",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 110, s: "Ds", name: "Darmstadtium", r: 7, c: 10, cat: "transition", config: "[Rn] 5f¹⁴ 6d⁸ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "281(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "unknown",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1994)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1994)",
        oxidation: "+10",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 111, s: "Rg", name: "Roentgenium", r: 7, c: 11, cat: "transition", config: "[Rn] 5f¹⁴ 6d⁹ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "280(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "unknown",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1994)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1994)",
        oxidation: "+11",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 112, s: "Cn", name: "Copernicium", r: 7, c: 12, cat: "transition", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "285(1)",
        phase: "Chất rắn",
        melting: "unknown",
        boiling: "unknown",
        density: "unknown",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1996)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1996)",
        oxidation: "+12",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 113, s: "Nh", name: "Nihonium", r: 7, c: 13, cat: "basic-metal", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "286(1)",
        phase: "Chất rắn",
        melting: "700 K (430 °C) (ước tính)",
        boiling: "1430 K (1130 °C) (ước tính)",
        density: "16 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2004)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2004)",
        oxidation: "+1",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 114, s: "Fl", name: "Flerovium", r: 7, c: 14, cat: "basic-metal", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "289(1)",
        phase: "Chất rắn",
        melting: "284 K (11 °C) (ước tính)",
        boiling: "unknown",
        density: "11,4 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1998)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (1998)",
        oxidation: "+2",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 115, s: "Mc", name: "Moscovium", r: 7, c: 15, cat: "basic-metal", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "288(1)",
        phase: "Chất rắn",
        melting: "670 K (400 °C) (ước tính)",
        boiling: "~1400 K (ước tính)",
        density: "13,5 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2003)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2003)",
        oxidation: "+3",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 116, s: "Lv", name: "Livermorium", r: 7, c: 16, cat: "basic-metal", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "292(1)",
        phase: "Chất rắn",
        melting: "637 - 780 K (364 - 507 °C) (ước tính)",
        boiling: "1135 K (862 °C) (ước tính)",
        density: "12,9 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2000)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2000)",
        oxidation: "+4",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 117, s: "Ts", name: "Tennessine", r: 7, c: 17, cat: "halogen", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "294(1)",
        phase: "Chất rắn",
        melting: "623 - 823 K (350 - 550 °C) (ước tính)",
        boiling: "883 K (610 °C) (ước tính)",
        density: "7,1 - 7,3 g/cm³ (ước tính)",
        discovery: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2003)",
        namedBy: "Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2003)",
        oxidation: "+1,+5",
        electronegativity: "1,3 (Pauling) (ước tính)"
    }},
    { n: 118, s: "Og", name: "Oganesson", r: 7, c: 18, cat: "noble", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", wikiData : {
        appearance: "Không rõ (rất hiếm và phóng xạ)",
        mass: "294(1)",
        phase: "Chất rắn",
        melting: "325 K (52 °C) (ước tính)",
        boiling:" 450 K (177 °C) (ước tính)",
        density:"7,2 g/cm³ (ước tính)",
        discovery:"Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2002)",
        namedBy:"Glenn T. Seaborg, Albert Ghiorso, Robert Elber và Torbjørn Sikkeland (2002)",
        oxidation:"+8",
        electronegativity:"1,3 (Pauling) (ước tính)"
    }}
];
